stolostron/deploy

- README.md
- start.sh
Adding a little more help for macOS users
> macOS enhancements for start.sh

- README.md
- clean-clusters.sh
- multiclusterhub-operator/uninstall.sh
- multiclusterhub/uninstall.sh
Add more cleanup
Installation was failing after uninstall.
Needed a way to clean up nicely the Hive clusterDeployments
> More clean up commands

- start.sh
The last change disabled the prompt for version. We need to decide if we want the default approach to NOT ask for a version, but until then, we should prompt for a version.
> Bring the prompt back

- multiclusterhub/example-multiclusterhub-cr.yaml
Preparing this PR to merge once this PR- https://github.com/open-cluster-management/multicloudhub-operator/pull/135 is merged into release
> Removes unnecessary values from MCH CR

- multiclusterhub-operator/uninstall.sh
- multiclusterhub/uninstall.sh
Doesn't let uninstall.sh stall if install failed
Resolves https://github.com/open-cluster-management/backlog/issues/1341
> Handle case were helmrelease resource doesn't exist

- CONTRIBUTING.md
- README.md
> resolve issue #38

- README.md
@tpouyer 
Based on testathon feedback in https://trello.com/c/XSD4CW3Y/2-tc101-installation-acm-on-ocp-43
@bcpswope FYI... This change (and any wordsmith changes) should make its way to https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/install/install_connected.md.    Please let me know if I should open a doc issue too
> Add info about snapshot.ver

- clean-clusters.sh
- start.sh
Address the following issues:
- issue #43
- improve validation, chech for valid oc version
- fix bug with cluster-cleanup missing namespace on delete cmd
> Prepare for testathon

- uninstall.sh
> [BUG][UNINSTALL]uninstall needs to verify oc connection

- hack/nuke.sh
- multiclusterhub/uninstall.sh
Remove finalizers in nuke.sh 
Remove source of hanging when deleting bad install
> Remove finalizers on nuke; Catch error from deleted helmrelease CRD

- README.md
- multiclusterhub/example-multiclusterhub-cr.yaml
Updating deploy as part of PR - https://github.com/open-cluster-management/multicloudhub-operator/pull/201
> Update MCH API to v1beta1

- multiclusterhub/uninstall.sh
Delete Search CRD post-uninstall
Waiting on change from Search to handle CRD deletion in https://github.com/open-cluster-management/backlog/issues/1794
> Delete search CRD

- hack/nuke.sh
- multiclusterhub/uninstall.sh
The user preference crd's apigroup has been updated, and the cleanup scripts need to reflect the new change.
> Update user preference crd apigroup

- README.md
- multiclusterhub/example-multiclusterhub-cr.yaml
Updates to deploy as part of PR - https://github.com/open-cluster-management/multicloudhub-operator/pull/209
Need to update with proper snapshot
> Move overridable fields to overrides

- hack/nuke.sh
- multiclusterhub/uninstall.sh
- Add the new ClusterRole and ClusterRoleBindings delete commands
New ClusterRole and ClusterRoleBinding required additional delete commands
Re-install can fail if these Kubernetes resources are not removed.
> Nuke & Uninstall

- resources/policies/policy-auth-provider.yaml
- resources/policies/policy-container-security.yaml
- resources/policies/policy-scc.yaml
Create additional policies to demonstrate:
- Configuring an OCP Authentication Provider for htpasswd
- Configuring the Container Security Operator and detect when image vulnerabilities exist. 
Provide additional examples for education and demonstration.
> Add more example policies

- demo/README.md
- demo/app/guestbook/README.md
- demo/app/guestbook/application.yaml
- resources/apps/guestbook-app.yaml
- Apply a different namespace for the app, re-using OCM namespace is not recommended.
- Updated readme
- Added a namespace and adjusted the channel to use that namespace
- Added a `remove command`
> App update

- README.md
- acm-operator/uninstall.sh
- multicluster-hub-operator/uninstall.sh
- multiclusterhub/example-multiclusterhub-cr.yaml
Relevant issue: [2555](https://github.com/open-cluster-management/backlog/issues/2555)
PR on Deploy repo:  https://github.com/open-cluster-management/deploy/pull/92
> Hub API Rename

- hack/nuke.sh
Adds a delete of search and managedclsuter clusterrolebinding, clusrerrole, and serviceaccounts.
> Adding deletion of search and managedcluster artifacts.

- hack/nuke.sh
The new CRDs that are added by registration-operator are not being cleaned up.
> Update nuke to remove registration CRDs

- docs/cleanup-offline-managed-cluster.md
- hack/cleanup-managed-cluster.sh
Added a hack script and corresponding docs for offline managed cluster cleanup.
Issue: https://github.com/open-cluster-management/backlog/issues/3210#issuecomment-655721843
Currently there is no easy way users can cleanup an offline & detached managed cluster, so we created this script to help.
> add offline managed cluster cleanup script

- README.md
It does what it says on the box.
> Add cluster conditions to downstream instructions

- community-subscriptions/hive-op.yaml
- community-subscriptions/kustomization.yaml
- community-subscriptions/subscription-op.yaml
- start.sh
- uninstall.sh
> explicit community operator subscriptions for non-bundle install

- dev/start.sh
Change to use installer full test suite
> Update wording and s3 logic

- hack/nuke.sh
> add webhook deletion to nuke

- clean-clusters.sh
For issue https://github.com/open-cluster-management/backlog/issues/5065
> fix for issue 5065

- start.sh
Default to a composite bundle.
> Default to composite bundle.

- README.md
- start.sh
Now that the MCH provides a detailed status throughout and at the end of deploy, we can use that status to detect when the mch is online and the install has succeeded, the current status of the install, and, in the case of a failed deploy, the components that failed to install.  
If the user is attempting to install OCM/ACM 2.0 and below, the behavior remains the same.  For 2.1 releases and above, the output will appear as follows:
with `--watch` and `DEBUG` unset or non-true:
```
#####
Wait for multicluster-operators-application to reach running state (4min).
* STATUS: multicluster-operators-application-85ffdb5874-fvxj5               3/4     Running     0          36s
* STATUS: multicluster-operators-application-85ffdb5874-fvxj5               3/4     Running     0          40s
* …
```
> Poll MCH status for 2.1.X+ deploys

- addons/observability/README.md
- addons/observability/example-observability-cr.yaml
- addons/observability/kustomization.yaml
- addons/observability/namespace.yaml
- addons/observability/reset.sh
- addons/observability/start.sh
- addons/observability/thanos.yaml
Added ability to deploy the new Observability Custom Resource instance.
Make it easier for devs/users to begin working with/testing Observability.
> Observability

- demo/app/devapp/devapp.yaml
The PlacementRule needs to be updated for the latest API changes.
The rule in use is deprecated.
(Discussion originated on Slack: https://coreos.slack.com/archives/CUEMQ631C/p1601995087020200)
> Update devapp.yaml PlacementRule

- README.md
> Remove baremetal activation instructions

- README.md
There were references to the 1.x builds which are no longer valid and were removed.
Separately, I moved sections for the downstream build further down so that early adopters don't believe this is required for their adoption. 
> Update README.md for downstream

- README.md
We need to remove non-external-facing contact email addresses - mine included!
> [Hotfix] Remove gurnben's email address

- hack/cleanup-managed-cluster.sh
* add additional resource for clean up for 2.1 release
* needed for clean managed cluster import
> 2.1 appliedmanifestwork cleanup

- version.sh
> add command to show RHACM version

- start.sh
Do grammar gooderly through smol change
> Do grammar gooder

- multiclusterhub/example-multiclusterhub-cr.yaml
Reverts open-cluster-management/deploy#185
> Revert "Update example-multiclusterhub-cr.yaml"

- README.md
- start.sh
Signed-off-by: Joshua Packer <jpacker@redhat.com>
Add search support flag.
An easy way to enable search during deployment
> Add support to activate search

- multiclusterengine/README.md
- multiclusterengine/start.sh
> Add MultiCluster Engine Downstream Deploy instructions

- multiclusterengine/start.sh
> Update multiclusterengine downstream image name

- README.md
This PR fixes some formatting in the README.
> Fix some formatting in README.md and improve docs

- demo/app/devapp/devapp.yaml
yaml indentation for channel snippet
> channel indentation

- multiclusterengine/README.md
- multiclusterengine/operator/subscription.yaml
> Update channel to stable-2.0

- idp-management/README.md
- idp-management/operator/catalogsource.yaml
- idp-management/operator/kustomization.yaml
- idp-management/operator/operatorgroup.yaml
- idp-management/operator/subscription.yaml
- idp-management/start.sh
Signed-off-by: Chris Ahl <cahl@redhat.com>
Adding ability to use the deploy repo to install `identity configuration management for Kubernetes`
Some of this change is based on info in https://github.com/open-cluster-management/backlog/issues/17484
> Add IDP start.sh stuff

- .github/PULL_REQUEST_TEMPLATE.md
- start.sh
Missed some references with my initial rename PR
> Add missing references

- start.sh
**Description of the change: Ensures Annotation override is defined in MCH spec during downstream installations.**
> Ensure 'mch-imageRepository' is added when defined

- multiclusterengine/multicluster_v1alpha1_multiclusterengine.yaml
This PR only affects the deploy of MCE in standalone mode
https://github.com/stolostron/backlog/issues/19242
https://github.com/stolostron/backlog/issues/19242
> Update MCE to v1

- upgrade.sh
https://github.com/stolostron/backlog/issues/18728
**Description of the change:** Fixes upgrade script
> Fix upgrade script

- start.sh
If a `pull-secret.yaml` exists but `QUAY_TOKEN` has been provided, patch the secret with the token.
If I want to use a different secret, I'd prefer to specify it in `QUAY_TOKEN` instead of having to delete my existing secret.
> Override pull-secret when QUAY_TOKEN is provided

- upgrade.sh
> Deploy MCE catalogsource on upgrade

- upgrade.sh
Changes to accommodate for upgrade in 2.5
> Mce upgrade fix

- docs/deploy-from-brew.md
Signed-off-by: Tesshu Flower <tflower@redhat.com>
Some small updates for the install from brew docs based on trying to follow the steps.  The main change is to add some links to docs on how to log in/create acct for kerberos IPA.REDHAT.COM - steps there can be hard to find.
> Doc updates for deploy-from-brew

- uninstall.sh
> Fix uninstall.sh for oc 4.10 versions

- README.md
Upstream builds are fully public, and downstream builds are internal only!  Let's update our documentation to reflect that!
> Update README to reflect publicly available upstream builds and private downstream builds

- multiclusterengine/upgrade.sh
Signed-off-by: Joshua Packer <jpacker@redhat.com>
* Allow upgrade and downgrade between releases.  Example: 2.0 => 2.1
* I wanted to upgrade to backplane-2.1.0 snapshots.
> Add support to upgrade from one version of backplane to another

- start.sh
Signed-off-by: Cameron Wall <cwall@redhat.com>
added more verbose status for the MCE subcomponents
help with the ease of debugging
> add mce status

- multiclusterhub/example-multiclusterhub-cr.yaml
Removed hardcoded annotation values to unblock MCE.
> removed unnecessary hardcoded annotations

- multiclusterengine/start.sh
- multiclusterengine/upgrade.sh
* Add support for multiple channels. The channel changes depending on the major release of the snapshot.  ie. 2.0 vs 2.1
* Add DOWNSTREAM support to MCE upgrade.sh
* Installing new major releases
* Upgrade downstream releases
> Downstream MCE support with channels

- multiclusterengine/start.sh
Signed-off-by: Ray Harris <raharris@redhat.com>
added code to use gsed on mac instead of sed
sed on mac has an issue with the -i option. using gsed makes the -i option consistent across OS es.
> multiclusterengine/start.sh: fix sed for mac

- hack/cleanup-managed-cluster.sh
Added klusterlets.operator.open-cluster-management.io to cleanup-managed-cluster.sh to cleanup the crds.
It resolves issue #179 . Closes #179
> add  klusterlets crd to the cleanup script
