- start.sh
- Remove work-around for clusterregistry CRD.
- No longer required
> This is no longer required. Stop deleting CRD

- README.md
Update README instructions to reference the `subscription` CRD explicitly
The creation of the `subscription.apps.open-cluster-management.io` (AKA `appsub`) CRD overwrites the `subscription` label. Making this command explicit in the README will prevent confusion. (Alternatively, we could use `sub` instead of the full name.)
(See short discussion at https://coreos.slack.com/archives/CUEMEHRA9/p1585058260084000)
> Make subscription check explicit

- demo/spoke/start.sh
- start.sh
- Check for default storageClass in start.sh script, abort on not found 
closes issue #20 
- Hide AWS key and secrete key from console output in demo/spoke/start.sh script.
- help user avoid confusion if no default storageClass defined in their targeted OCP cluster
- for security reasons hide AWS key and secret key from console output.
> check for default storageClass and hide aws keys from console output

- uninstall.sh
Display the target cluster before proceeding with the uninstall.
I'm always worried that I'll wipe out a cluster that isn't mine. This should prevent users from accidentally deleting the wrong cluster.
> Display target cluster before uninstall

- start.sh
Changed `if [[ $SC_RESOLVE =~ (default) ]];`, to take (default) literal
Originally it was letting the conditional pass if user's current project is default when using `./start.sh`.
> Change conditional to be more strict with default

- multiclusterhub-operator/subscription.yaml
- multiclusterhub-operator/uninstall.sh
- multiclusterhub/example-multiclusterhub-cr.yaml
Related issues:
https://github.com/open-cluster-management/backlog/issues/1219
https://github.com/open-cluster-management/backlog/issues/1607
Needs to be merged with:
https://github.com/open-cluster-management/multicloudhub-operator/pull/177
> remove optional version, update operator version to 1.0.0

- demo/app/devapp/devapp.yaml
Signed-off-by: Xiangjing Li <xiangli@redhat.com>
subscribe nginx v1.36 as the old v1.20 nginx helm chart is bundling deployment template with apiversion: v1beta1, which is not supported in openshift platform, where deployment with apiversion: v1 is applied 
> subscribe nginx v1.36

- README.md
For the love of Pete, tell us what your quay ID is via rover
Tell people to update their rover profile with quay ID
Randos come in to #forum-acm and ask for access to quay.  Problem is... we don't have a way to know what their ID is.  So to limit the back-and-forth, tell them how to help themselves first by updating their rover profile.
> Add instructions to update rover profile with quay

- resources/policies/policy-container-security.yaml
The `PlacementRule` for one of the policies used a label that should have been a `string` but was interpreted as a `bool`. Added quotes to ensure it is read as a `string`.
> Convert the matchLabels to use strings instead of bools

- demo/app/guestbook/application.yaml
The guestbook-app was using the older form of using a ConfigMap to reference a path in GitHub. 
Align the default example with the current usage patterns.
> Update app to use annotation for github-path

- start.sh
`deploy` s on fresh clusters will fail with an error:
```
namespace/open-cluster-management created
secret/multiclusterhub-operator-pull-secret created
Error from server (AlreadyExists): error when creating "prereqs/": serviceaccounts "default" already exists
```
In essence, `kubectl apply -k prereqs/` plans that its going to create the ns and the default service account, but doesn't realize that by creating the ns it has already created the default service account, and needs to update the default sa differently or risk getting an "AlreadyExists" error.  That's the closest theory we have.  It falls apart a bit, because creating the NS and then deleting it, then re-running the deploy repo also works which is interesting to say the least. But either way, pulling the NS creation out of the …
> Resolve "AlreadyExists" error when creating prereq SA on fresh clusters

- README.md
Because ACM 1.X.X deploys via an artifact named acm-custom-registry (which uses the COMPOSITE_BUNDLE), you need to set `COMPOSITE_BUNDLE=true` to deploy 1.X.X builds!  Adding a note about this to the readme.
> Adding a note to export COMPOSITE_BUNDLE=true if you're deploying 1.X.X

- README.md
Need to add `quay.io` to the path.
> Fixed CUSTOM_REGISTRY_REPO path for acm-d

- start.sh
This is a hotfix to make the `--watch` parameter actually obey the detected pod count.  This was missed in an initial PR that modified the env var, we found a location where the env var was not used, instead the pod count was verbosely stated.  Sorry for the double PR, should've caught that the first time 😉
> Fix Dynamic Pod Count Polling

- acm-operator/uninstall.sh
- hack/nuke.sh
- multicluster-hub-operator/uninstall.sh
Delete `kui-proxy-scc` object via nuke script
The Canary builds are reporting that `kui-proxy-scc` object was not getting cleaned up on uninstall, and subsequent installs are failing. Ref: https://github.com/open-cluster-management/backlog/issues/2878
> Delete scc objects nuke scripts only, not uninstall

- hack/nuke.sh
Workaround for #2915 and delete the open-cluster-management-hub namespace for 2.X builds!
> Add workaround for #2915 and delete the open-cluster-management-hub namespace

- multiclusterhub/uninstall.sh
This increased wait duration should resolve certain helmrelease cleanup issues we've observed when running uninstall and nuke back-to-back.
> Bump wait duration for HelmRelease cleanup

- start.sh
imageTagSuffix is not present in the example CR, so this command does nothing.
Issue: https://github.com/open-cluster-management/backlog/issues/2732
> Remove imageTagSuffix sed command

- start.sh
Remove check for a default storage class in `start.sh`.
Since Mongo and ETCD are removed from the project, a storage class is no longer required for install
Closes https://github.com/open-cluster-management/backlog/issues/3182
> Remove storageclass check

- multiclusterhub/example-multiclusterhub-cr.yaml
- start.sh
These changes will automatically inject the CUSTOM_REGISTRY_REPO (default quay.io/open-cluster-management) as the "mch-imageRepository" annotation in the MCH resource that is applied by the deploy repo.  This should allow successful deploys via Hive with downstream builds from quay.io/acm-d.
> Add "mch-imageRepository" annotation to mch resource. 

- start.sh
It does what it says on the box.  You can now override SUBSCRIPTION_CHANNEL with another value, important for 2.1 deploys where you need to set SUBSCRIPTION_CHANNEL to release-2.1.
> Parameterize the SUBSCRIPTION_CHANNEL variable

- start.sh
It does what it says on the box again!
> check for the correct pod count on 2.1.X deploys  as well as 2.0.X deploys

- start.sh
Fixes an issue where 2.1.0 builds think they're 1.0.X builds because regex is a lossy art.
> Fix version detection

- README.md
- start.sh
Resolves https://github.com/open-cluster-management/backlog/issues/3638
This PR detects the major release version of ACM/OCM from the snapshot text and forms a subscription channel based on the value of the COMPOSITE_BUNDLE toggle.  This should resolve issues when deploying the composite vs non-composite bundle upstream and should also allow greater flexibility moving forward to new OCM versions. This PR also allows the user to override the subscription channel wholesale. 
latest 2.1.0 upstream w/ COMPOSITE_BUNDLE=true
latest 2.1.0 upstream w/ COMPOSITE_BUNDLE=false
latest 2.0.0 upstream w/ COMPOSITE_BUNDLE=true
latest 2.0.0 upstream w/ COMPOSITE_BUNDLE=false
v2.0.0-RC3 downstream w/ COMPOSITE_BUNDLE=true
> Auto-Detect Subscription Channel for Composite and Non-Composite Bundles

- clean-clusters.sh
Added deletion of managedcluster & klusterletaddonconfig
(wait 120 seconds & force delete)
Current ./uninstall.sh doesn't delete managedcluster, with the latest installer webhook changes, the uninstall.sh  can be not working properly.
Tested it can uninstall rhacm 2.0/2.1 with created/imported clusters
**Note:** I'm not sure do we still support rhacm 1.0's uninstall, so I didn't remove the old cluster deletion logic.
> update clean-clusters.sh to delete managedcluster 

- hack/cleanup-managed-cluster.sh
Fix minor typo in log message: `CustomResourceDefination` --> `CustomResourceDefinition`
This script is now documented in the RHACM docs, so we should have it as polished as possible.
> Fix typo in managed cleanup script log message

- dev/start.sh
The installer tests were updated to include their entire codebase, resulting in a change in results file destination.  This change will change the mount destination for the results directory to reflect their internal changes.
> Move installer test results file mount destination

- README.md
Fix for downstream ACM 2.x instructions to use `base64 -w 0` instead of just `base64` this will ensure there are no line breaks when doing a base64 encoding on the QUAY_TOKEN.
Was causing issues when the base64 encoded value is broken up into different lines when deploying a downstream build.
> Readme update to base64 encoding to avoid line breaks

- start.sh
Our new default value for `COMPOSITE_BUNDLE` was backed out in the previous PR, we need to replay it over the new changes.
> [hotfix] replay COMPOSITE_BUNDLE default that was backed out in a previous merge

- README.md
We tell the user to create an ICSP which, inadvertently, included a typo referencing `openshfit4` instead of `openshift4`.
> Fix a typo in the ICSP

- clean-clusters.sh
- uninstall.sh
Originally the uninstall script would leave provider connections if they existed outside ACM namespaces.  We felt this was not good to leave provider connection secrets lying around, so we added cleanup code to uninstall.  However, many developers take advantage of the ability to create provider connections in the default namespace and have them persist across uninstall/install.
This change adds a flag to the uninstall script to allow the extra provider connections to be kept.  Default behavior is still to delete them.
Change for issue https://github.com/open-cluster-management/backlog/issues/5095
> add option to keep provider connections

- README.md
We should update the readme to include the name of the pull secret that must be edited on a live cluster in order to install a downstream build!
> Add the name of the secret that must be edited for downstream builds.

- README.md
Recently, we had a number of external collaborators use our deploy repo.  The documentation mislead them, thinking they needed a rover profile and access to our private slack workspace.  This patch updates the readme to remove rover references and reference the CICD team's shared email as the best first external point of contact.  This email address can be updated later FYI @berenss
> Update README to inform non-Red-Hatters how to gain access to pre-GA ACM

- start.sh
This change now checks for `n/n` containers running, rather than number specific.  
This change was motivated by a container count change for `multicluster-operators-application` - we only care that all containers start up when waiting for a pod, this change will accommodate the new container count and avoid such issues in the future.  
Addresses https://github.com/open-cluster-management/backlog/issues/7686
> check for n/n pods rather than a fixed number of pods in waitforpod

- start.sh
Added filter for `RC` named snapshots when deploying from downstream to remove the extra `v` i.e. `v2.1.1-RC4`
When deploying an `RC` snapshot from downstream the extra `v` in the snapshot name was causing an extra `v` to appear in the `STARTING_CSV` variable i.e. `STARTING_CSV=advanced-cluster-management.vv2.1.1-RC4` 
This fix will ensure the removal of the extra `v` i.e. `STARTING_CSV=advanced-cluster-management.v2.1.1-RC4`
Closes #7436
> fix downstream rc deployments

- uninstall.sh
This adds an additional step to uninstall.sh to remove the open-cluster-management namespace upon uninstall.
When trying to deploy downstream acm-d builds, I wanted to try a newer version, so I ran uninstall.sh but it appeared that I had to go further than what this script did to successfully re-run ./start.sh with a different release version. Once I'd deleted the namespace I was good to go.
I suspect that there's a reason why we don't want to clear up the namespace so suspect this PR will be rejected... but would be good to understand whether start.sh needs further work if a deployment has already been uninstalled prior?
> Adding in a step to remove the open-cluster-management namespace on uninstall

- hack/cleanup-managed-cluster.sh
Signed-off-by: Leena Jawale <ljawale@redhat.com>
Missing cleaning up klusterlet crd from cleanup-managedcluster script. Added it
> update cleanup-managedcluster script to add deletion of klusterlet crd

- clean-clusters.sh
Signed-off-by: Chris Ahl <cahl@redhat.com>
Need to update the uninstall to cleanup any credentials that are using the new label (as of 2.3)
> fix cleanup for new label in credentials

- OWNERS
This PR removes mdelder from the owners file to unblock [this PR](https://github.com/openshift/release/pull/19104#issuecomment-857010241) which drives OSCI Prow configuration for this repo.
> Update owners file to unblock prow config

- README.md
Update README to include accepting invitation at quay.io after CICD team gives you access.
I've never used quay.io before and didn't know this step was needed. My first try at a deploy failed as a result.
> Update README to include accepting invitation at quay.io

- brew-start.sh
- dev/lib/helpers.sh
- dev/start.sh
- start.sh
- Move `helpers.sh` to `dev/lib/helpers.sh`
- Use `waitForPod` from centralized location in all start scripts
- Exit early if an ImagePullBackoff is detected
> Use helpers.sh for waitForPod function and add early exit on `ImagePullBackoff`

- brew-start.sh
- dev/start.sh
- helpers.sh
- start.sh
Reverts open-cluster-management/deploy#208
This seems to have broken [CI Jobs](https://app.travis-ci.com/github/open-cluster-management/canary/jobs/541138861) so let's revert and I'll test this afternoon and find a patch.  This regex _should have_ worked!
> Revert "Use helpers.sh for waitForPod function and add early exit on `ImagePullBackoff`" temporarily

- README.md
- addons/downstream/image-content-source-policy.yaml
This PR adds an imageContentSourcePolicy entry for images that live in the `multicluster-engine` namespace of `registry.redhat.io`.  This is the namespace that will hold released images for the multicluster engine productized offering.
Signed-off-by: Joe Gdaniec <jgdaniec@redhat.com>
> Add ISCP entries for MCE (multicluster-engine)

- start.sh
Signed-off-by: Cameron Wall <cwall@redhat.com>
I added two bracketed if statements allowing the installation of the operator and multi-cluster hub to be skipped based on passing in environment variables.
In order to make changes to the CICD Canary tests, it was necessary to have the ability to split the installation of the operator and MCH
> add skip capabilities to installation based on environment variables

- start.sh
Signed-off-by: Joshua Packer <jpacker@redhat.com>
The `--search` parameter was not being applied to installations
Bug fix.
> Search was not be enabled by the flag, changed positioning in the script

- start.sh
- Remove `router-default` from canonical hostname (if it exists)
- The canonical hostname seems to begin with `router-default.apps.`
> Remove `router-default` from canonical hostname

- idp-management/identityconfig_v1alpha1_idpconfig.yaml
- idp-management/start.sh
Creation of IDPConfig CR as part of installation of `identity configuration management for Kubernetes` operator.
Some of this is based on the Zenhub issue https://github.com/open-cluster-management/backlog/issues/18373 
When the `IDPConfig` CR is created the idp installer controller will trigger the install of the the idp-mgmt-operator, the webhook and the dex-operator.
> Add creation of IDPConfig CR as part of start.sh for idp-management

- CONTRIBUTING.md
- README.md
- acm-operator/kustomization.yaml
- addons/observability/example-observability-cr.yaml
- demo/README.md
- demo/app/guestbook/application.yaml
- demo/kind/import/endpoint.yaml
- demo/kind/import/kustomization.yaml
- demo/kind/kind-cluster.yaml
- demo/policies/channel.yaml
- dev/acm-operator/kustomization.yaml
- dev/multicluster-hub-operator/kustomization.yaml
- dev/start.sh
- hack/nolimits.sh
- hack/nuke.sh
- multicluster-hub-operator/kustomization.yaml
- multiclusterengine/README.md
- multiclusterengine/start.sh
- multiclusterhub/uninstall.sh
First pass at changing org references to stolostron, I left the references to the project name as `open-cluster-management` but changed the quay request project to match the actual repo name.
Changes include:
Github Links
Quay Links
Registry Updates
> Change the github org name

- start.sh
- Update to use `/usr/local/bin/` instead of `~/bin/` for the `yq` installation
- Bail if the `yq` installation doesn't work
- `yq` is required, so we should be exiting the script rather than continuing forward if `yq` doesn't work
Followup to:
- https://github.com/stolostron/deploy/pull/224
> Bail on `yq` failure

- README.md
Hidden behind a URL link was a very outdated image reference; fix it
It was broken
> Move multiclusterhub-operator-index references

- start.sh
This PR enables search if `--watch` is enabled _or_ prints a message regarding enabling search if you don't instruct the script to watch for the install to be ready!
Resolves https://github.com/stolostron/backlog/issues/18195
> Enable search by default

- docs/deploy-from-brew.md
Signed-off-by: Tesshu Flower <tflower@redhat.com>
Original instructions said to modify the existing rhacm-repo ICSP for images in registry.redhat.io/rhacm2 but on some clusters there's a SelectorSyncSet which will revert this value back after a while.
Updating instead the custom example for the brew-registry ICSP to include a mirror for /rhacm2 path.
> Doc update - add a /rhacm2 mirror in icsp

- start.sh
Allow oc client 4.10.X to deploy ACM.
> Allow oc client 4.10 versions

- start.sh
Just not support lower than 4.3 and assuming a newer version of OC CLI is installed
> Removing OC Client Check

- README.md
Add documentation how to add a managed cluster by using downstream images.
It does not work to deploy managed clusters by following the [documentation](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.3/html/clusters/importing-a-target-managed-cluster-to-the-hub-cluster#importing-a-managed-cluster-with-the-cli) because some more tweaks are necessary.
A script may follow in the future but first I want to discuss the documentation and having an approve that this approach is correct.
> Add managed cluster documentation for downstream images

- .gitignore
- start.sh
The standalone console is deprecated. Rather than keeping the URL logic, it's more direct to provide the `oc` command to fetch the route alongside the new URL:
```
#####
* Red Hat ACM URL: https://console-openshift-console.apps.<base-domain>/multicloud/home/welcome
* NOTE: For RHACM versions <2.6 or OCP versions <4.10, the console link can be found by running:
oc -n open-cluster-management get routes multicloud-console -o jsonpath='{.status.ingress[0].host}'
#####
```
This also sets an ignore for the `applied-mch` directory.
> Remove logic around the standalone console

- README.md
- upgrade-snapshot.sh
Includes:
README.md
upgrade-snapshot.sh [--watch] [--debug]
* Allow developers to move easily from one snapshot to the next. This is useful to pick up fixes or to bump your development build to the end of development sprint for a given Train without reinstalling.
*  Updated the README.md for the fact that Quay no longer has personal tokens and you must get a Robot + Token.
* Imporve developer workflows by enhancing the DevTooling
> Add upgrade-snapshot.sh script, for moving development builds between snapshots
